package cmd

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/carlos/sigil/internal/crypto"
	"github.com/carlos/sigil/internal/vaultstore"
)

func TestDefaultConfigPath_underHomeSigil(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)
	resetCmdState(t)
	got, err := DefaultConfigPath()
	if err != nil {
		t.Fatal(err)
	}
	want, err := filepath.Abs(filepath.Join(home, ".sigil", "vault.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	gotAbs, err := filepath.Abs(got)
	if err != nil {
		t.Fatal(err)
	}
	if gotAbs != want {
		t.Fatalf("DefaultConfigPath: got %q, want %q", gotAbs, want)
	}
}

func TestRunInit_rejectsExistingVaultYAML(t *testing.T) {
	cmdExecuteMu.Lock()
	defer cmdExecuteMu.Unlock()
	resetCmdState(t)

	home := t.TempDir()
	t.Setenv("HOME", home)
	sigilDir := filepath.Join(home, ".sigil")
	if err := os.MkdirAll(sigilDir, 0o700); err != nil {
		t.Fatal(err)
	}
	vaultYAML := filepath.Join(sigilDir, "vault.yaml")
	if err := os.WriteFile(vaultYAML, []byte("project: x\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	vaultAbs, err := filepath.Abs(vaultYAML)
	if err != nil {
		t.Fatal(err)
	}

	rootCmd.SetArgs([]string{"init", "--config", vaultAbs})
	err = rootCmd.Execute()
	if err == nil {
		t.Fatal("expected error when vault.yaml already exists")
	}
	if !strings.Contains(err.Error(), "already initialized") {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestRunInit_rejectsExistingSecretEnc(t *testing.T) {
	cmdExecuteMu.Lock()
	defer cmdExecuteMu.Unlock()
	resetCmdState(t)

	home := t.TempDir()
	t.Setenv("HOME", home)
	sigilDir := filepath.Join(home, ".sigil")
	if err := os.MkdirAll(sigilDir, 0o700); err != nil {
		t.Fatal(err)
	}
	secretPath := filepath.Join(sigilDir, "secret.enc")
	if err := os.WriteFile(secretPath, []byte("dummy"), 0o600); err != nil {
		t.Fatal(err)
	}

	cfgDir := t.TempDir()
	cfgAbsent := filepath.Join(cfgDir, "vault.yaml")
	cfgAbs, err := filepath.Abs(cfgAbsent)
	if err != nil {
		t.Fatal(err)
	}

	rootCmd.SetArgs([]string{"init", "--config", cfgAbs})
	err = rootCmd.Execute()
	if err == nil {
		t.Fatal("expected error when secret.enc already exists")
	}
	if !strings.Contains(err.Error(), "user data already exists") {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestRunInit_createsKeyStoreAndConfigNoEncFiles(t *testing.T) {
	cmdExecuteMu.Lock()
	defer cmdExecuteMu.Unlock()
	resetCmdState(t)

	home := t.TempDir()
	t.Setenv("HOME", home)
	cfgDir := t.TempDir()
	cfgPath := filepath.Join(cfgDir, "vault.yaml")
	cfgAbs, err := filepath.Abs(cfgPath)
	if err != nil {
		t.Fatal(err)
	}

	vaultPass := "unit-test-vault-pass"
	fixedAutoKey := "unitAutoGeneratedEncryptionKey32!!"

	oldPC := initPromptConfirmPassword
	oldC := initConfirm
	oldGen := initGenerateKey
	initPromptConfirmPassword = func(_, _ string) (string, error) { return vaultPass, nil }
	initConfirm = func(string, bool) (bool, error) { return true, nil }
	initGenerateKey = func(int) (string, error) { return fixedAutoKey, nil }
	t.Cleanup(func() {
		initPromptConfirmPassword = oldPC
		initConfirm = oldC
		initGenerateKey = oldGen
	})

	rootCmd.SetArgs([]string{"init", "--config", cfgAbs})
	if err := rootCmd.Execute(); err != nil {
		t.Fatal(err)
	}

	if _, err := os.Stat(cfgAbs); err != nil {
		t.Fatalf("vault.yaml: %v", err)
	}
	sigilDir := filepath.Join(home, ".sigil")
	secretPath := filepath.Join(sigilDir, "secret.enc")
	blob, err := os.ReadFile(secretPath)
	if err != nil {
		t.Fatalf("secret.enc: %v", err)
	}
	plain, err := crypto.UnwrapSecret(vaultPass, blob)
	if err != nil {
		t.Fatalf("UnwrapSecret: %v", err)
	}
	if plain != fixedAutoKey {
		t.Fatalf("unexpected encryption key plaintext: %q", plain)
	}

	vaultsDir := filepath.Join(sigilDir, "vaults")
	names, err := vaultstore.ListEncBasenames(vaultsDir)
	if err != nil {
		t.Fatal(err)
	}
	if len(names) != 0 {
		t.Fatalf("expected no .enc files after init, got %v", names)
	}
}

func TestRunInit_createsVaultWithDefaultConfigPath(t *testing.T) {
	cmdExecuteMu.Lock()
	defer cmdExecuteMu.Unlock()
	resetCmdState(t)

	home := t.TempDir()
	t.Setenv("HOME", home)
	t.Chdir(t.TempDir())

	vaultPass := "unit-pass-2"
	fixedAutoKey := "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"

	oldPC := initPromptConfirmPassword
	oldC := initConfirm
	oldGen := initGenerateKey
	initPromptConfirmPassword = func(_, _ string) (string, error) { return vaultPass, nil }
	initConfirm = func(string, bool) (bool, error) { return true, nil }
	initGenerateKey = func(int) (string, error) { return fixedAutoKey, nil }
	t.Cleanup(func() {
		initPromptConfirmPassword = oldPC
		initConfirm = oldC
		initGenerateKey = oldGen
	})

	rootCmd.SetArgs([]string{"init"})
	if err := rootCmd.Execute(); err != nil {
		t.Fatal(err)
	}

	cfgPath := filepath.Join(home, ".sigil", "vault.yaml")
	if _, err := os.Stat(cfgPath); err != nil {
		t.Fatalf("default vault.yaml: %v", err)
	}
}
